// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoInventario;

#nullable disable

namespace ProyectoInventario.Migrations
{
    [DbContext(typeof(ComputadoraContext))]
    partial class ComputadoraContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProyectoInventario.Modelos.Computadora", b =>
                {
                    b.Property<string>("NumInvId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiscoDuroId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImpresoraId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Mac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemoriaRamId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MicroProcesadorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MonitorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MotherBoardId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NombreArea")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NombreDepartamento")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NombreUsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NumIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TecladoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NumInvId");

                    b.HasIndex("DiscoDuroId");

                    b.HasIndex("ImpresoraId");

                    b.HasIndex("MemoriaRamId");

                    b.HasIndex("MicroProcesadorId");

                    b.HasIndex("MonitorId");

                    b.HasIndex("MotherBoardId");

                    b.HasIndex("NombreUsuarioId");

                    b.HasIndex("TecladoId");

                    b.ToTable("Computadoras", (string)null);

                    b.HasData(
                        new
                        {
                            NumInvId = "563411",
                            DiscoDuroId = "2813qwd8q",
                            ImpresoraId = "67854",
                            Mac = "3c-4r-55-rf-4g-66-22",
                            MemoriaRamId = "7h7g8f8fke9gtr54t6yac52",
                            MicroProcesadorId = "fe2de405c38e4c90ac52",
                            MonitorId = "7843",
                            MotherBoardId = "7h7g8f8fke964744t6yac12",
                            Nombre = "OFC-ECO-CAB",
                            NombreArea = "UEB Economia",
                            NombreDepartamento = "Finanzas",
                            NombreUsuarioId = "juan.perez",
                            NumIp = "172.19.229.111",
                            TecladoId = "6731"
                        },
                        new
                        {
                            NumInvId = "89064",
                            DiscoDuroId = "58523eeee",
                            ImpresoraId = "78354",
                            Mac = "3c-4f-00-4f-4d-43-d3",
                            MemoriaRamId = "67tun7588nd7y7y4t6yac78",
                            MicroProcesadorId = "fe2de405c38e4c9034rt",
                            MonitorId = "4321",
                            MotherBoardId = "67tun7588nd7y7y4t6yrf54",
                            Nombre = "SSP-Tec-IOO",
                            NombreArea = "UEB Sancti Spiritus",
                            NombreDepartamento = "Tecnico",
                            NombreUsuarioId = "fernando",
                            NumIp = "172.19.229.111",
                            TecladoId = "67344"
                        });
                });

            modelBuilder.Entity("ProyectoInventario.Modelos.DiscoDuro", b =>
                {
                    b.Property<string>("NumSerieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Capacidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TipoConexion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NumSerieId");

                    b.ToTable("Discos Duro", (string)null);

                    b.HasData(
                        new
                        {
                            NumSerieId = "2813qwd8q",
                            Capacidad = "256gb",
                            Marca = "toshiba",
                            TipoConexion = "sata"
                        },
                        new
                        {
                            NumSerieId = "58523eeee",
                            Capacidad = "500gb",
                            Marca = "samsung",
                            TipoConexion = "sata"
                        });
                });

            modelBuilder.Entity("ProyectoInventario.Modelos.Display", b =>
                {
                    b.Property<string>("NumInvId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumSerie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NumInvId");

                    b.ToTable("Monitores", (string)null);

                    b.HasData(
                        new
                        {
                            NumInvId = "7843",
                            Marca = "Acer",
                            NumSerie = "7h7g8f8fke9gtr54t6yac52"
                        },
                        new
                        {
                            NumInvId = "4321",
                            Marca = "Samsung",
                            NumSerie = "7h7g8f8fke956rf67uuj43ed"
                        });
                });

            modelBuilder.Entity("ProyectoInventario.Modelos.Impresora", b =>
                {
                    b.Property<string>("NumInvId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NumSerie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NumInvId");

                    b.ToTable("Impresoras", (string)null);

                    b.HasData(
                        new
                        {
                            NumInvId = "67854",
                            Marca = "Epson",
                            NumSerie = "jjdj778sk66he4535ef"
                        },
                        new
                        {
                            NumInvId = "78354",
                            Marca = "HP",
                            NumSerie = "jjdj778skld887f333f"
                        });
                });

            modelBuilder.Entity("ProyectoInventario.Modelos.MemoriaRam", b =>
                {
                    b.Property<string>("NumSerieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Capacidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tecnologia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NumSerieId");

                    b.ToTable("Memorias Ram", (string)null);

                    b.HasData(
                        new
                        {
                            NumSerieId = "7h7g8f8fke9gtr54t6yac52",
                            Capacidad = "4gb",
                            Marca = "Kingston",
                            Tecnologia = "DD4"
                        },
                        new
                        {
                            NumSerieId = "67tun7588nd7y7y4t6yac78",
                            Capacidad = "2gb",
                            Marca = "HyperX",
                            Tecnologia = "DD3"
                        });
                });

            modelBuilder.Entity("ProyectoInventario.Modelos.MicroProcesador", b =>
                {
                    b.Property<string>("NumSerieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tecnologia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NumSerieId");

                    b.ToTable("Microprocesadores", (string)null);

                    b.HasData(
                        new
                        {
                            NumSerieId = "fe2de405c38e4c90ac52",
                            Marca = "Intel",
                            Tecnologia = "Core-I-5"
                        },
                        new
                        {
                            NumSerieId = "fe2de405c38e4c9034rt",
                            Marca = "AMD",
                            Tecnologia = "Core-I-20"
                        });
                });

            modelBuilder.Entity("ProyectoInventario.Modelos.MotherBoard", b =>
                {
                    b.Property<string>("NumSerieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NumSerieId");

                    b.ToTable("MotherBoards", (string)null);

                    b.HasData(
                        new
                        {
                            NumSerieId = "7h7g8f8fke964744t6yac12",
                            Marca = "Asus"
                        },
                        new
                        {
                            NumSerieId = "67tun7588nd7y7y4t6yrf54",
                            Marca = "DELL"
                        });
                });

            modelBuilder.Entity("ProyectoInventario.Modelos.Teclado", b =>
                {
                    b.Property<string>("NumInvId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumSerie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoConexion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NumInvId");

                    b.ToTable("Teclados", (string)null);

                    b.HasData(
                        new
                        {
                            NumInvId = "6731",
                            Marca = "DELL",
                            NumSerie = "7h7g8f8fke9gtr54t6y67uyh",
                            TipoConexion = "usb"
                        },
                        new
                        {
                            NumInvId = "67344",
                            Marca = "Delton",
                            NumSerie = "67tun7588nd7y7y4t6y45rtg",
                            TipoConexion = "usb"
                        });
                });

            modelBuilder.Entity("ProyectoInventario.Modelos.Usuario", b =>
                {
                    b.Property<string>("NombreUsuarioId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NombreArea")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreDepartamento")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("NombreUsuarioId");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            NombreUsuarioId = "juan.perez",
                            NombreArea = "Economia",
                            NombreCompleto = "Juan Perez",
                            NombreDepartamento = "Finanzas"
                        },
                        new
                        {
                            NombreUsuarioId = "fernando",
                            NombreArea = "UEB Sancti-Spiritus",
                            NombreCompleto = "Fernando Alonso",
                            NombreDepartamento = "Tecnico"
                        });
                });

            modelBuilder.Entity("ProyectoInventario.Modelos.Computadora", b =>
                {
                    b.HasOne("ProyectoInventario.Modelos.DiscoDuro", "DiscoDuro")
                        .WithMany("Computadora")
                        .HasForeignKey("DiscoDuroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoInventario.Modelos.Impresora", "Impresora")
                        .WithMany("Computadora")
                        .HasForeignKey("ImpresoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoInventario.Modelos.MemoriaRam", "MemoriaRam")
                        .WithMany("Computadora")
                        .HasForeignKey("MemoriaRamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoInventario.Modelos.MicroProcesador", "MicroProcesador")
                        .WithMany("Computadora")
                        .HasForeignKey("MicroProcesadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoInventario.Modelos.Display", "Display")
                        .WithMany("Computadora")
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoInventario.Modelos.MotherBoard", "MotherBoard")
                        .WithMany("Computadoras")
                        .HasForeignKey("MotherBoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoInventario.Modelos.Usuario", "Usuario")
                        .WithMany("Computadora")
                        .HasForeignKey("NombreUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoInventario.Modelos.Teclado", "Teclado")
                        .WithMany("Computadora")
                        .HasForeignKey("TecladoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscoDuro");

                    b.Navigation("Display");

                    b.Navigation("Impresora");

                    b.Navigation("MemoriaRam");

                    b.Navigation("MicroProcesador");

                    b.Navigation("MotherBoard");

                    b.Navigation("Teclado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoInventario.Modelos.DiscoDuro", b =>
                {
                    b.Navigation("Computadora");
                });

            modelBuilder.Entity("ProyectoInventario.Modelos.Display", b =>
                {
                    b.Navigation("Computadora");
                });

            modelBuilder.Entity("ProyectoInventario.Modelos.Impresora", b =>
                {
                    b.Navigation("Computadora");
                });

            modelBuilder.Entity("ProyectoInventario.Modelos.MemoriaRam", b =>
                {
                    b.Navigation("Computadora");
                });

            modelBuilder.Entity("ProyectoInventario.Modelos.MicroProcesador", b =>
                {
                    b.Navigation("Computadora");
                });

            modelBuilder.Entity("ProyectoInventario.Modelos.MotherBoard", b =>
                {
                    b.Navigation("Computadoras");
                });

            modelBuilder.Entity("ProyectoInventario.Modelos.Teclado", b =>
                {
                    b.Navigation("Computadora");
                });

            modelBuilder.Entity("ProyectoInventario.Modelos.Usuario", b =>
                {
                    b.Navigation("Computadora");
                });
#pragma warning restore 612, 618
        }
    }
}
